name: Hyperliquid DCA Bot Automated Trade

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule (e.g., every day at 9:00 AM UTC)
  # Use https://crontab.guru to customize your schedule
  schedule:
    - cron: '0 9 * * 1'

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DCA Trading Script
      env:
        HYPERLIQUID_PRIVATE_KEY: ${{ secrets.HYPERLIQUID_PRIVATE_KEY }}
        HYPERLIQUID_WALLET_ADDRESS: ${{ secrets.HYPERLIQUID_WALLET_ADDRESS }}
      run: |
        cd $GITHUB_WORKSPACE
        python check_and_trade.py 